import { chromium, devices } from "playwright";
import fs from "node:fs";
const SP = "/private/tmp/claude-501/-Users-contratacr/a4175880-a9ef-4fa9-8f6a-c39dfb1891e4/scratchpad";
const env = Object.fromEntries(fs.readFileSync(".env.test","utf8").split("\n").filter(l=>/^[A-Z_]+=/.test(l)).map(l=>{const i=l.indexOf("=");return [l.slice(0,i), l.slice(i+1).replace(/^"|"$/g,"")];}));
const base = process.env.BASE || "https://test.contratacr.com";
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices["iPhone 14"], viewport: { width: 390, height: 844 } });
const p = await ctx.newPage();
const errores = [];
p.on("console", (m) => { if (m.type() === "error") errores.push(m.text().slice(0, 300)); });
p.on("pageerror", (e) => errores.push("pageerror: " + String(e).slice(0, 300)));
p.on("response", async (r) => { if (r.url().includes("/api/quotes") ) errores.push(`API ${r.status()} ${r.url()} :: ${(await r.text().catch(()=>"")).slice(0,300)}`); });
await p.goto(`${base}/es/empleos/publicar`, { waitUntil: "domcontentloaded" }); await p.waitForTimeout(3500);
const entrar = p.getByRole("link", { name: /Inicia sesi/i }).or(p.getByRole("button", { name: /Inicia sesi/i })).first();
if (await entrar.isVisible().catch(() => false)) { await entrar.click(); await p.waitForTimeout(2000); }
await p.locator('input[type="email"]').first().fill("e2e.pro@contratacr.test");
await p.locator('input[type="password"]').first().fill(env.E2E_TEST_PASSWORD || env.REGRESSION_TEST_PASSWORD);
await p.locator('input[type="password"]').first().press("Enter"); await p.waitForTimeout(8000);
await p.goto(`${base}/es/dashboard/profesional?mode=offer&tab=quotes`, { waitUntil: "domcontentloaded" }); await p.waitForTimeout(7000);
const txt = (await p.locator("body").innerText()).replace(/\s+/g, " ");
console.log("URL:", p.url());
console.log("PANTALLA:", txt.slice(0, 300));
console.log("ERRORES:", errores.slice(0, 6).join("\n---\n") || "ninguno");
await p.screenshot({ path: `${SP}/test-cotizar.png` });
await b.close();
